#pragma config(Sensor, S1, ultra, sensorEV3_Ultrasonic)
#pragma config(Sensor, S2, color, sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Motor, motorA, left, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorB, right, tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Made by Abdihakim Bashe, Sumeet Sara, and Kirubel Bogale
//MSE 110 Fall 2019, Dr. Narimani
//Project 1, LINE FOLLOWER

// Light Sensor Values calibrated for being 2cm above the ground
// DO NOT SET SPEED ABOVE 22 IN ONE MOTOR AND 2 IN THE SECONDARY MOTOR, OTHERWISE IT CANNOT MAKE LEFT AND RIGHT TURNS

// Main Process
task main() {
// Repeat Forever
    while (true) {
        // Get the Distance Reading on the Ultrasonic sensor in cm
        float distance;
        distance = getUSDistance(ultra);
        //Declare variables for RGB
        int redValue;
        int greenValue;
        int blueValue;
        // Declare the variable that controls which action the robot does when it see's the object
        int objectcolor;

        getColorRGB(color, redValue, greenValue, blueValue);

        // If the Green Value from the Light Sensor is less than 8, the line must be blue
        // Set objectcolor to 1
        if ((greenValue) < 6) {
            objectcolor = 1;
        }

        //If the Green Value from the Light Sesnor is greater than 8 and less than 12, the line must be green
        // Set objectcolor to 2
        if ((greenValue) > 6 && (greenValue) < 10) {
            objectcolor = 2;
        }


        // Enter this loop if the Ultrasonic does not detect an object within 10cm
        while ((distance) > 10) {

            // Get the Distance Reading on the Ultrasonic sensor in cm
            distance = getUSDistance(ultra);
            // Get RGB Values
            getColorRGB(color, redValue, greenValue, blueValue);

            //Enter this loop if the Green RGB Value is less than 10
            // Meaning the sensor is on a Green or Blue surface
            if ((greenValue) < 10) {
                // Robot will turn to the right
                setMotorSpeed(left, 22);
                setMotorSpeed(right, 2);
            }
                // Otherwise
            else {
                // Robot will turn to the left
                setMotorSpeed(left, 2);
                setMotorSpeed(right, 22);
            }
        }


        // Enter this loop if the Ultrasonic detects an object within 10cm
        while ((distance) < 10) {

            // Get RGB and Distance values from Sensors
            distance = getUSDistance(ultra);
            getColorRGB(color, redValue, greenValue, blueValue);

            // If the Robot started on a Green Line, the objectcolor variable was set to 2
            // If the Robot encounters an object on the Green Line, it will do a 180* turn and return to the starting position
            if ((objectcolor) == 2) {

                /*Stop moving, beep for 2 seconds, stop, do a 180 degree turn */
                setMotorSpeed(left, 0);
                setMotorSpeed(right, 0);
                playTone(300, 200);
                sleep(2000);
                setMotorSpeed(left, -40);
                setMotorSpeed(right, 40);
                sleep(1000);
                // Get Distance Values to check the loop condition
                distance = getUSDistance(ultra);
            }

            // If the Robot started on a Blue Line, the objectcolor variable was set to 1
            /* If the Robot encounters an object on the Blue Line, it will push the object forward out of the way
                     and continue the line*/
            if ((objectcolor) == 1) {

                /* Stop motors, beep for two seconds, then push the object forward
                then go back to previous spot and continue line tracking*/
                setMotorSpeed(left, 0);
                setMotorSpeed(right, 0);
                playTone(300, 200);
                sleep(2000);
                setMotorSpeed(left, 100);
                setMotorSpeed(right, 100);
                sleep(1000);
                setMotorSpeed(left, -100);
                setMotorSpeed(right, -100);
                sleep(1000);
                // Get Distance Values to check the loop condition
                distance = getUSDistance(ultra);
            }

            // END of Distance <10 loop
        }

        // End of Infinite Loop
    }
}

// End of Program
